name: test on Windows

on:
    push:
        branches: ["main","dev"]
    pull_request: 
        branches: ["main"]

jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: test
              run: ./script/test_windows.ps1